format = '$all'
scan_timeout = 10
add_newline = true

[battery]
full_symbol = '🔋 '
charging_symbol = '⚡️ '
discharging_symbol = '💀 '
disabled = true

[[battery.display]]
threshold = 20
style = 'bold red'

[character]
format = 'λ '

[cmd_duration]
min_time = 500
show_milliseconds = true

[directory]
truncation_length = 5
truncation_symbol = '…/'

[docker_context]
format = 'via [🐋 $context](blue bold)'

[dotnet]
style = 'bold blue'

[hostname]
ssh_only = false
format = '[@$hostname](bold dimmed grey) '

[status]
style = 'bg:blue'
symbol = '💣 '
format = '[\[$symbol$status\]]($style) '
disabled = false

[time]
disabled = true

[username]
style_user = 'blue bold'
style_root = 'white bold'
format = '[$user]($style) '
disabled = false
show_always = true
