format = '$all'
scan_timeout = 10
add_newline = true

[battery]
full_symbol = '🔋 '
charging_symbol = '⚡️ '
discharging_symbol = '💀 '

[[battery.display]]
threshold = 20
style = 'bold red'

[character]
format = 'λ '

[cmd_duration]
min_time = 500
show_milliseconds = true

[directory]
truncation_length = 5
truncation_symbol = '…/'
read_only = " ro"

[docker_context]
symbol = "docker "

[hostname]
ssh_only = false
format = '[@$hostname](bold dimmed grey) '

[localip]
ssh_only = true
format = "@[$localipv4](bold red) "
disabled = false

[status]
style = 'bg:blue'
symbol = '💣 '
format = '[\[$symbol$status\]]($style) '
disabled = false

[time]
disabled = true

[username]
style_user = 'blue bold'
style_root = 'white bold'
format = '[$user]($style) '
disabled = false
show_always = true

[git_commit]
tag_symbol = " tag "

[git_branch]
symbol = "branch:"

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[aws]
symbol = "aws "

[c]
symbol = "C "

[cobol]
symbol = "cobol "

[conda]
symbol = "conda "

[crystal]
symbol = "cr "

[cmake]
symbol = "cmake "

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "
style = 'bold blue'

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

[golang]
symbol = "go "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "

[julia]
symbol = "jl "

[kotlin]
symbol = "kt "

[nodejs]
symbol = "nodejs "

[memory_usage]
symbol = "memory "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "

[package]
symbol = "pkg "

[perl]
symbol = "pl "

[php]
symbol = "php "

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "

[python]
symbol = "py "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[scala]
symbol = "scala "

[spack]
symbol = "spack "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "
